### ISSUE TITLE
Color management

### ISSUE THREAD

**Issue by ChoiZ** [Elao/curvytron#100]
I think it can be great to have a color separation, for distinguish 2 players. And add a rule to prohibit the background color.
For color separation, I think you can use color frequency or a percentage of R,G,B. At less 15% of difference for R+G+B.

**Comment by Tom32i** [comment]
Yep, definitely.
I just added it to our to-do list.

Thanks for the feedback, I'll let you know when it's done!

**Comment by ChoiZ** [comment]
Maybe when the countdown appear you can display nickname near each player. If both are red, we can know who is one red or the other one.
