### ISSUE TITLE
Invisible walls feedback

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#106]
When an invisible wall bonus is activated nobody cares who has triggered the bonus, but everybody can use the invisible walls to go on the other side of the playground.
However ONLY the player who has triggered the bonus is warned when the invisible walls will be deactivated (the bonus icon starts blinking). ONLY him can predict the moment when the walls will become normal again.

As it's a "bonus-for-all" it would be better to put some feedbacks or highlights on the wall itself to warn every play that it will come back to normal soon.

**Comment by Tom32i** [comment]
Shout be better now.
