### ISSUE TITLE
It's possible to have an empty player name.

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#109]
As it's possible to change the player name in the lobby (waiting for players to be ready), it's possible to enter ingame with no name.

![noname](https://cloud.githubusercontent.com/assets/18822/6286411/73cd0b58-b907-11e4-8ab1-629ea408fe07.jpg)

**Comment by Tom32i** [comment]
How did you do that? :full_moon_with_face:

**Comment by Tom32i** [comment]
Oh well, ok I'll fix it :new_moon_with_face:

**Comment by Tom32i** [comment]
Fixed!
