### ISSUE TITLE
Spectator should be displayed.

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#111]
In spectate mode your name is not displayed.
You're not in the player (or any spectator) list.
In the chat your name is "Anonymous" even if you have set a name.

It could be interesting for players to know that they are watched, and to know who watches them.
Scenario: You're playing with your friends, and another one is joining your game... you might want to stop the current game to restart one with the newcomer.

**Comment by Tom32i** [comment]
Yep :+1:
