### ISSUE TITLE
Feature: notification on player join

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#117]
Classic scenario: 
1. I create a game
2. I'm alone
3. nobody joins
4. I start lurking the Internet and scroll among thousands of pictures of pugs
5. while I fall in love with cuty-pie, a 2 yrs old cute pug, someone joins my room and set ready
6. after few minutes he leaves the room
7. I come back and I'm still alone and sad in the room

It would be awesome to have sound + tab notification to warn players when someone joins.

**Comment by Tom32i** [comment]
Done!
