### ISSUE TITLE
The game doesn't start in case of kick

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#122]
If everyone in the room is marked as ready except one player, and if this player is kicked... the game doesn't start even if everyone is ready.

**Comment by Tom32i** [comment]
Yeah... it's kind of a feature, I didn't want the game to start "without" an actual action from a player.
Do you think the game should start when everyone is ready "just" because someone left?

**Comment by lvictorino** [comment]
It's important to only have one behaviour for a specific action. 
If the condition to enter a game is "have every players marked as ready"... then on kick the game should start if "every players are marked as ready".
The only other possibility I see would be to have a "game leader" who pushes a "start game" button (bad idea).

**Comment by Tom32i** [comment]
Alright, thanks for the insight. Again.
I'll make the change :)
