### ISSUE TITLE
No SFX on the second game

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#125]
On Opera 27.0:

The first game plays SFX correctly, but once the game is finished and I get back to the lobby, if a new game starts SFX are not played anymore.

**Comment by Tom32i** [comment]
Weird. Thanks for the feedback, I'll look into it tonight.

**Comment by Tom32i** [comment]
I couldn't reproduce it on Opera 27 on OS X, could you tell me if you still get the issue?

**Comment by lvictorino** [comment]
Well... now it works.

**Comment by Tom32i** [comment]
All right, it has probably been fixed along the way, I worked on a lot of fix lately :)
