### ISSUE TITLE
Bug: It's possible to enter in a room without actually being in a room

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#127]
I joined a room but I was not in the player list.

![curvybug](https://cloud.githubusercontent.com/assets/18822/6349318/894cb378-bc29-11e4-8f49-ff6a832c28d8.jpg)

**Comment by Tom32i** [comment]
I'm working on it :fire: :fire_engine:

**Comment by Tom32i** [comment]
Fixed (or at least not happened in a while...).
