### ISSUE TITLE
Suggestion: change the way AFK is triggered

### ISSUE THREAD

**Issue by ronanlevesque** [Elao/curvytron#154]
I think it would be nice that the AFK icon for a player in a room appears when a certain time has elapsed rather than making it appear everytime the tab focus is lost (so that people won't jump in and out when they see a room with 1 to few people with that AFK icon).

- Cap. Yolo :)

**Comment by JeremyJames** [comment]
:+1:

**Comment by Tom32i** [comment]
Done! Thanks @ronanlevesque : good point.
