### ISSUE TITLE
Disconnected from the server when idling in the main lobby

### ISSUE THREAD

**Issue by emerick42** [Elao/curvytron#159]
I'm under Mac OS X, using Chrome. When I stay idle on the main lobby (the homepage) for too long, I get the error page indicating that the server is not responding anymore and that I should refresh the page.

I think the idle time has to be more than 1 minute (but I don't really know, it's just an estimate).

**Comment by Tom32i** [comment]
Fixed by https://github.com/Elao/curvytron/commit/ce6f611a303e6163b4b0708d67e769181289f67c :)
