### ISSUE TITLE
Error: createjs is not defined

### ISSUE THREAD

**Issue by jamesottaway** [Elao/curvytron#190]
Running off a350275a307b2fca80f23ec54011eda685f9c4d3, I followed the instructions in `doc/installation.md` but I get the following error in the console:

```
Error: createjs is not defined
SoundManager@http://192.168.59.103/js/curvytron.js:7:17639
i@http://192.168.59.103/js/dependencies.js:1:20908
o@http://192.168.59.103/js/dependencies.js:1:21002
c/<@http://192.168.59.103/js/dependencies.js:1:19575
i@http://192.168.59.103/js/dependencies.js:1:20908
a/<@http://192.168.59.103/js/dependencies.js:1:19345
i@http://192.168.59.103/js/dependencies.js:1:20908
Be/A.$injector<@http://192.168.59.103/js/dependencies.js:1:21485
r@http://192.168.59.103/js/dependencies.js:1:20540
i@http://192.168.59.103/js/dependencies.js:1:20877
en/this.$get</</<@http://192.168.59.103/js/dependencies.js:2:9754
b/<@http://192.168.59.103/js/dependencies.js:2:516
o@http://192.168.59.103/js/dependencies.js:1:3799
b@http://192.168.59.103/js/dependencies.js:2:500
s@http://192.168.59.103/js/dependencies.js:1:28574
V/<@http://192.168.59.103/js/dependencies.js:1:28064
L/r@http://192.168.59.103/js/dependencies.js:1:29063
l@http://192.168.59.103/js/dependencies.js:1:31244
ua</<.link/<@http://192.168.59.103/js/dependencies.js:4:20429
Kn/this.$get</h.prototype.$digest@http://192.168.59.103/js/dependencies.js:3:3153
Kn/this.$get</h.prototype.$apply@http://192.168.59.103/js/dependencies.js:3:4636
Q/s/<@http://192.168.59.103/js/dependencies.js:1:9444
i@http://192.168.59.103/js/dependencies.js:1:20908
Q/s@http://192.168.59.103/js/dependencies.js:1:9365
Q@http://192.168.59.103/js/dependencies.js:1:9651
X@http://192.168.59.103/js/dependencies.js:1:8900
@http://192.168.59.103/js/dependencies.js:5:6963
r@http://192.168.59.103/js/dependencies.js:3:27735
je/n@http://192.168.59.103/js/dependencies.js:1:17961
```

I'm running node v0.12.4 and I've tried things like `bower cache clean` but it never seems to work.

Any ideas?

**Comment by Tom32i** [comment]
Hey!

I've updated the doc to add the missing `bower install` instruction:
https://github.com/Elao/curvytron/blob/master/doc/installation.md

Please ensure you did a `npm install`, then `bower install`, then `gulp`.

Can you confirm that it solves the problem?

**Comment by jamesottaway** [comment]
From what I can tell, [`npm install` triggers `bower install`](https://github.com/Elao/curvytron/blob/2c2077ea40bc6a5980a677f9d15e80546b924fa8/package.json#L54).

**Comment by lutangar** [comment]
Check your console again but in some case, you might have run into something like:
> npm WARN cannot run in wd curvytron@1.4.4 bower install

Try to run `bower install` manually.

**Comment by jamesottaway** [comment]
Yeah, I tried an explicit `bower install` but it doesn't fix the issue.

I checked versions of the other libraries in case there's any issues there:
- NPM v2.10.1
- Bower v1.4.1
- Gulp v3.8.11

**Comment by Tom32i** [comment]
Weird, I just checked and I have the exact same version as you.

- Does the `gulp` command says something about an error?
- Do you have the `web/js/curvytron.js` and `web/js/dependencies.js` files in your repository?
- How do you access the app?

The problem might come from a specific bower package: `createjs-soundjs`, can you check you have a `/bower_components/createjs-soundjs` folder?

**Comment by lutangar** [comment]
The problem comes from the createjs-soundjs build name `'soundjs-0.6.0.min.js', it changes as the version changed.
Version should be fixed in `the bower.json`.

**Comment by Tom32i** [comment]
Nice one dude! :+1:
