### ISSUE TITLE
Private rooms!

### ISSUE THREAD

**Issue by Tom32i** [Elao/curvytron#79]
Quick poll, should we:
- Show private rooms in the list but ask for password?
- Or just don't show them and tell the user to share the link?

**Comment by lvictorino** [comment]
Go with *private with password*.
It keeps the game alive. If you come to the lobby with 256000 hidden private room you can't see, the first thing you'll think is "nobody play this stupid game". You'd be wrong, but chances are that you would never come back and see how wrong you were.

In addition to password I strongly recomand URL sharing.

**Comment by Tom32i** [comment]
Trello card created:
- You can create a private room
- The room will generate its 4 digits password
- You can join the room by entering the password in the rooms list
- You can also give your friends the url and they will access  the room without entering the password
